version: "3.2"

services:
    client:
        build:
            context: ./client/
            dockerfile: Dockerfile
        # restart: always
        ports:
            - "3000:3000"
        # working_dir: /client/src/app
        entrypoint: ["npm", "start"]
        volumes:
            - ./client/:/app
            - /app/node_modules
        links:
            - backend
        container_name: movies-search-client
        environment:
            backend_URL: backend
        # depends_on:
        #     - backend

    backend:
        build:
            context: ./backend/
            dockerfile: Dockerfile
        ports:
            - "3001:3001"
        volumes:
            - ./backend/:/app
            - /app/node_modules
        links:
            - mysql
        container_name: movies-search-backend
        # command: npm run seed:run
        environment:
            DB_HOST: mysql
            JWT_SECRET: ${JWT_SECRET}
            BACKEND_PORT: ${BACKEND_PORT-3001}
            TYPEORM_CONNECTION: "mysql"
            TYPEORM_HOST: mysql
            TYPEORM_USERNAME: "admin"
            TYPEORM_PASSWORD: "admin"
            TYPEORM_DATABASE: "movies"
            TYPEORM_PORT: "3306"
            TYPEORM_ENTITIES: "src/**/*.entity{.ts,.js}"
    
    mysql:
        image: "mysql:5.7.24"
        container_name: "typeorm-mysql"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "admin"
            MYSQL_USER: "admin"
            MYSQL_PASSWORD: "admin"
            MYSQL_DATABASE: "movies"

